from . import ai_assistant
from . import batch
from . import category
from . import customer
from . import dashboard
from . import expense
from . import medicine
from . import purchase
from . import purchase_lines
from . import res_config_settings
from . import sale
from . import sale_return
from . import sale_order_lines
from . import stock_adjustment
from . import stock_move
from . import supplier
from . import period_report_wizard
